/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // // By default, Docusaurus generates a sidebar from the docs folder structure
  integrationsSidebar: [
    { type: "doc", id: "integrations/index" },
    { type: "doc", id: "integrations/community" },
    {
      type: "category",
      label: "Observability",
      link: { type: "doc", id: "integrations/observability_index" },
      items: [
        {
          type: "category",
          label: "Contributing to Integrations",
          items: [
            {
              type: "autogenerated",
              dirName: "contribute_integration"
            }
          ],
        },
        {
          type: "category",
          label: "OpenTelemetry",
          items: [
            "observability/opentelemetry_v2_migration",
            "observability/opentelemetry_v2",
            "observability/opentelemetry_integration",
          ],
        },
        {
          type: "category",
          label: "LLM observability platforms",
          items: [
            "observability/argilla",
            "observability/athina_integration",
            "observability/braintrust",
            "observability/opik_integration",
            "observability/deepeval_integration",
            "observability/helicone_integration",
            "observability/humanloop",
            "observability/langfuse_integration",
            "observability/langsmith_integration",
            "observability/literalai_integration",
            "observability/logfire_integration",
            "observability/lunary_integration",
            "observability/mavvrik",
            "observability/mlflow",
            "observability/promptlayer_integration",
            "observability/qualifire_integration",
            "observability/wandb_integration",
          ],
        },
        {
          type: "category",
          label: "Infrastructure backends",
          items: [
            "observability/azure_sentinel",
            "observability/datadog",
            "observability/gcs_bucket_integration",
            "observability/newrelic",
            "observability/posthog_integration",
            "observability/sentry",
            "observability/signoz",
            "observability/slack_integration",
            "observability/splunk_observability_cloud",
            "observability/sumologic_integration",
            "observability/supabase_integration",
          ],
        },
        {
          type: "category",
          label: "Cost, billing, and usage",
          items: [
            "observability/cloudzero",
            "observability/focus",
            "observability/greenscale_integration",
            "observability/lago",
            "observability/openmeter",
            "observability/ramp_integration",
            "observability/vantage",
          ],
        },
        {
          type: "category",
          label: "Callbacks and customization",
          items: [
            "observability/callbacks",
            "observability/custom_callback",
            "observability/generic_api",
            "observability/raw_request_response",
            "observability/scrub_data",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Guardrail Providers",
      link: {
        type: "generated-index",
        title: "Guardrail Providers",
        description: "Add safety and content filtering to LLM calls",
        slug: "/guardrail_providers"
      },
      items: [
        {
          type: "category",
          label: "Contributing to Guardrails",
          items: [
            "adding_provider/generic_guardrail_api",
            "adding_provider/simple_guardrail_tutorial",
            "adding_provider/adding_guardrail_support",
          ]
        },
        {
          type: "doc",
          id: "proxy/guardrails/team_based_guardrails",
          label: "Team Bring-Your-Own Guardrails",
        },
        ...[
          "proxy/guardrails/qohash_qostodian_nexus",
          "proxy/guardrails/qualifire",
          "proxy/guardrails/aim_security",
          "proxy/guardrails/onyx_security",
          "proxy/guardrails/aporia_api",
          "proxy/guardrails/azure_content_guardrail",
          "proxy/guardrails/bedrock",
          "proxy/guardrails/crowdstrike_aidr",
          "proxy/guardrails/enkryptai",
          "proxy/guardrails/ibm_guardrails",
          "proxy/guardrails/grayswan",
          "proxy/guardrails/hiddenlayer",
          "proxy/guardrails/lasso_security",
          "proxy/guardrails/guardrails_ai",
          "proxy/guardrails/lakera_ai",
          "proxy/guardrails/microsoft_purview",
          "proxy/guardrails/model_armor",
          "proxy/guardrails/noma_security",
          "proxy/guardrails/dynamoai",
          "proxy/guardrails/openai_moderation",
          "proxy/guardrails/pangea",
          "proxy/guardrails/pillar_security",
          "proxy/guardrails/repelloai",
          "proxy/guardrails/promptguard",
          "proxy/guardrails/pii_masking_v2",
          "proxy/guardrails/panw_prisma_airs",
          "proxy/guardrails/secret_detection",
          "proxy/guardrails/sensitive_data_routing",
          "proxy/guardrails/custom_guardrail",
          "proxy/guardrails/custom_code_guardrail",
          "proxy/guardrails/prompt_injection",
          "proxy/guardrails/tool_permission",
          "proxy/guardrails/rubrik",
          "proxy/guardrails/zscaler_ai_guard",
          "proxy/guardrails/javelin",
          "proxy/guardrails/akto",
          "proxy/guardrails/vigil_guard",
          "proxy/guardrails/xecguard",
        ].sort(),
      ],
    },
    {
      type: "category",
      label: "Alerting & Monitoring",
      items: [
        "proxy/alerting",
        "proxy/pagerduty",
        "proxy/prometheus",
        "proxy/pyroscope_profiling"
      ]
    },
    {
      type: "category",
      label: "Cost Optimization",
      items: [
        {
          type: "link",
          label: "Prompt Compression",
          href: "/docs/completion/prompt_compression#server-side-callback-loop-v1messages",
        },
        "proxy/headroom",
      ]
    },
    {
      type: "category",
      label: "[Beta] Prompt Management",
      items: [
        {
          type: "category",
          label: "Contributing to Prompt Management",
          items: [
            "adding_provider/generic_prompt_management_api",
          ]
        },
        "proxy/litellm_prompt_management",
        "proxy/custom_prompt_management",
        "proxy/native_litellm_prompt",
        "proxy/prompt_management",
        "proxy/arize_phoenix_prompts"
      ]
    },
    {
      type: "category",
      label: "AI Tools",
      link: {
        type: "generated-index",
        title: "AI Tools",
        description: "Integrate LiteLLM with AI tools like OpenWebUI, Claude Code, and more",
        slug: "/ai_tools"
      },
      items: [
        "tutorials/openweb_ui",
        {
          type: "category",
          label: "Claude Code",
          items: [
            "claude_code_compatibility",
            "tutorials/claude_code_cut_costs",
            "tutorials/claude_responses_api",
            "tutorials/claude_code_max_subscription",
            "tutorials/claude_code_byok",
            "tutorials/claude_code_customer_tracking",
            "tutorials/claude_code_budget_statusline",
            "tutorials/claude_code_prompt_cache_routing",
            "tutorials/claude_code_websearch",
            "tutorials/claude_mcp",
            "tutorials/claude_non_anthropic_models",
            "tutorials/claude_code_plugin_marketplace",
            "tutorials/claude_code_beta_headers",
            "claude_code_context_management",
          ]
        },
        "tutorials/claude_desktop_cowork",
        "tutorials/opencode_integration",
        "tutorials/openclaw_integration",
        "tutorials/cursor_integration",
        "tutorials/github_copilot_integration",
        "tutorials/litellm_gemini_cli",
        "tutorials/litellm_qwen_code_cli",
        "tutorials/openai_codex",
        "tutorials/retool_assist",
        "tutorials/cost_tracking_coding"
      ]
    },
    {
      type: "category",
      label: "Agent SDKs",
      link: {
        type: "generated-index",
        title: "Agent SDKs",
        description: "Use LiteLLM with agent frameworks and SDKs",
        slug: "/agent_sdks"
      },
      items: [
        "tutorials/openai_agents_sdk",
        "tutorials/claude_agent_sdk",
        "tutorials/copilotkit_sdk",
        "tutorials/google_adk",
        "tutorials/google_genai_sdk",
        "tutorials/livekit_xai_realtime",
        "integrations/letta",
        { type: "doc", id: "tutorials/scalekit_agentkit", label: "Scalekit with LiteLLM" },
        { type: "doc", id: "tutorials/instructor", label: "Instructor with LiteLLM" },
        { type: "doc", id: "langchain/langchain", label: "LangChain with LiteLLM" },
        "projects/openai-agents"
      ]
    },
    {
      type: "category",
      label: "Manage with AI Agents",
      link: {
        type: "generated-index",
        title: "Manage with AI Agents",
        description: "Use AI agents to manage your LiteLLM deployment — create users, teams, keys, models, and more via natural language.",
        slug: "/manage_with_ai_agents"
      },
      items: [
        "tutorials/claude_code_skills",
      ]
    },

  ],
  // But you can create a sidebar manually
  tutorialSidebar: [
    // ════════════════════════════════════════════════════════════
    // GET STARTED
    // ════════════════════════════════════════════════════════════
    {
      type: "category",
      label: "Get Started",
      collapsible: false,
      collapsed: false,
      items: [
        { type: "doc", id: "index", label: "Quickstart" },
        { type: "link", label: "Models & Pricing", href: "https://models.litellm.ai" },
        { type: "link", label: "Changelog", href: "/release_notes" },
      ],
    },

    {
      type: "category",
      label: "LiteLLM Python SDK",
      items: [
        {
          type: "link",
          label: "Quick Start",
          href: "/docs/#litellm-python-sdk",
        },
        {
          type: "category",
          label: "SDK Functions",
          items: [
            {
              type: "doc",
              id: "completion/input",
              label: "completion()",
            },
            {
              type: "doc",
              id: "embedding/supported_embedding",
              label: "embedding()",
            },
            {
              type: "doc",
              id: "response_api",
              label: "responses()",
            },
            {
              type: "doc",
              id: "text_completion",
              label