import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  releaseNotesSidebar: [
    {type: 'doc', id: 'index', label: 'Release Notes'},
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
