import {readdir, readFile, writeFile} from 'node:fs/promises';
import process from 'node:process';

const BLOG_DIR = new URL('../../blog/', import.meta.url);
const OUTPUT_URL = new URL('../data/posts.snapshot.js', import.meta.url);
const TAG = 'rust-migration';
const HEADER = '// Generated by scripts/update-posts.mjs from the blog posts tagged rust-migration. Do not edit by hand.\n';

// Reads the fields this page needs from a post's frontmatter. Values are plain
// scalars or one-line `[a, b]` lists, which is how the blog writes them.
function frontmatter(source) {
  const match = /^---\n([\s\S]*?)\n---/.exec(source);
  const fields = {};
  for (const line of (match?.[1] ?? '').split('\n')) {
    const field = /^([A-Za-z_]+):\s*(.*)$/.exec(line);
    if (field) {
      fields[field[1]] = field[2].trim().replace(/^["']|["']$/g, '');
    }
  }
  return fields;
}

// A date with no zone is read as UTC, so the snapshot does not depend on the machine.
const toUtc = value => new Date(/(Z|[+-]\d\d:?\d\d)$/.test(value) || !value.includes('T') ? value : `${value}Z`).toISOString();

const tagsOf = fields => (fields.tags ?? '').replace(/^\[|\]$/g, '').split(',').map(tag => tag.trim());

// A post lives at `blog/<folder>/index.md` and is served at `/blog/<slug>`.
async function readPost(folder) {
  let source;
  try {
    source = await readFile(new URL(`${folder}/index.md`, BLOG_DIR), 'utf8');
  } catch {
    return null;
  }
  const fields = frontmatter(source);
  if (!tagsOf(fields).includes(TAG)) {
    return null;
  }
  return {
    title: fields.title,
    permalink: `/blog/${fields.slug ?? folder}`,
    date: toUtc(fields.date),
  };
}

async function generateSnapshot() {
  const folders = (await readdir(BLOG_DIR, {withFileTypes: true})).filter(entry => entry.isDirectory());
  const posts = (await Promise.all(folders.map(entry => readPost(entry.name))))
    .filter(Boolean)
    .sort((left, right) => new Date(right.date) - new Date(left.date));
  return `${HEADER}export const posts = ${JSON.stringify(posts, null, 2)};\n`;
}

const snapshot = await generateSnapshot();
if (process.argv.includes('--check')) {
  const current = await readFile(OUTPUT_URL, 'utf8').catch(() => '');
  if (current !== snapshot) {
    console.error('Rust migration posts are stale. Run npm run update:rust-migration');
    process.exitCode = 1;
  }
} else {
  await writeFile(OUTPUT_URL, snapshot);
  console.log(`Updated ${OUTPUT_URL.pathname}`);
}
